# Generated by Django 4.1.2 on 2024-11-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategoryPost', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='category_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categorypost'),
        ),
    ]
