# Generated by Django 4.1.2 on 2024-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_categorypost_post_likes_post_category_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
