from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Profile_CV)
admin.site.register(WorkExperience)
admin.site.register(AcademicEducation)
admin.site.register(HardSkillUser)
admin.site.register(HardSkill)
admin.site.register(SoftSkillUser)
admin.site.register(SoftSkill)
admin.site.register(LanguageUser)
admin.site.register(Language)
admin.site.register(SectorUser)
admin.site.register(Sector)
admin.site.register(CategoryUser)
admin.site.register(Category)
admin.site.register(IncorporationUser)
admin.site.register(Incorporation)
admin.site.register(Volunteering)
admin.site.register(Project)
admin.site.register(Publication)
admin.site.register(RecognitionAward)
admin.site.register(CertificationCourse)
admin.site.register(User_cv)