# Generated by Django 5.1.1 on 2024-11-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("academy_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_education", models.BooleanField(blank=True, null=True)),
                ("references", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CertificationCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("academy_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_course", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_hard_skill", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Incorporation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_incorporation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_language", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("role", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RecognitionAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("entity", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_soft_skill", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteering_position", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_volunteering", models.BooleanField(blank=True, null=True)),
                ("entity_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("references", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_job", models.BooleanField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("references", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HardSkillUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("level_skill", models.IntegerField(max_length=5)),
                (
                    "hard_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.hardskill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncorporationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.incorporation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LanguageUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("certifications", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_sector", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectorUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkillUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "soft_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.softskill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile_CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img_1_profile",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                (
                    "img_2_profile",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                (
                    "img_3_profile",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                (
                    "img_4_profile",
                    models.ImageField(blank=True, upload_to="profile_images/"),
                ),
                ("address", models.CharField(max_length=255)),
                ("phone_1", models.CharField(max_length=20)),
                ("phone_2", models.CharField(max_length=20)),
                ("email_1", models.EmailField(max_length=254)),
                ("email_2", models.EmailField(blank=True, max_length=254, null=True)),
                ("dni", models.CharField(max_length=20, unique=True)),
                ("biography", models.TextField(blank=True, null=True)),
                ("open_to_work", models.BooleanField(blank=True, null=True)),
                ("vehicle", models.BooleanField(null=True)),
                ("disability", models.BooleanField(blank=True, null=True)),
                ("disability_percentage", models.IntegerField(blank=True, null=True)),
                (
                    "academic_educations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.academiceducation",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.categoryuser",
                    ),
                ),
                (
                    "certifications_courses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.certificationcourse",
                    ),
                ),
                (
                    "hard_skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.hardskilluser",
                    ),
                ),
                (
                    "incorporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.incorporationuser",
                    ),
                ),
                (
                    "languages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.languageuser",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.project",
                    ),
                ),
                (
                    "publications",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.publication",
                    ),
                ),
                (
                    "recognitions_awards",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.recognitionaward",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.sectoruser",
                    ),
                ),
                (
                    "soft_skills",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.softskilluser",
                    ),
                ),
                (
                    "volunteerings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.volunteering",
                    ),
                ),
                (
                    "work_experiences",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.workexperience",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_cv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urlCV", models.URLField(blank=True, null=True, unique=True)),
                ("template", models.CharField(max_length=255)),
                ("has_img_profile", models.BooleanField(blank=True, null=True)),
                ("has_address", models.BooleanField(blank=True, null=True)),
                ("has_phone_1", models.BooleanField(blank=True, null=True)),
                ("has_phone_2", models.BooleanField(blank=True, null=True)),
                ("has_email_1", models.BooleanField(blank=True, null=True)),
                ("has_email_2", models.BooleanField(blank=True, null=True)),
                ("has_dni", models.BooleanField(blank=True, null=True)),
                ("has_url", models.BooleanField(blank=True, null=True)),
                ("has_biography", models.BooleanField(blank=True, null=True)),
                ("has_open_to_work", models.BooleanField(blank=True, null=True)),
                ("has_vehicle", models.BooleanField(null=True)),
                ("has_disability", models.BooleanField(blank=True, null=True)),
                (
                    "has_disability_percentage",
                    models.BooleanField(blank=True, null=True),
                ),
                ("has_incorporation", models.BooleanField(blank=True, null=True)),
                ("has_sector", models.BooleanField(blank=True, null=True)),
                ("has_category", models.BooleanField(blank=True, null=True)),
                ("has_work_experiences", models.BooleanField(blank=True, null=True)),
                ("has_hard_skills", models.BooleanField(blank=True, null=True)),
                ("has_soft_skills", models.BooleanField(blank=True, null=True)),
                ("has_languages", models.BooleanField(blank=True, null=True)),
                ("has_academic_educations", models.BooleanField(blank=True, null=True)),
                ("has_volunteerings", models.BooleanField(blank=True, null=True)),
                ("has_projects", models.BooleanField(blank=True, null=True)),
                ("has_publications", models.BooleanField(blank=True, null=True)),
                ("has_recognitions_awards", models.BooleanField(blank=True, null=True)),
                (
                    "has_certifications_courses",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "profile_cv",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile_cv.profile_cv",
                    ),
                ),
            ],
        ),
    ]
