# Generated by Django 3.2.12 on 2024-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('profile_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_cv',
            name='certifications_courses',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Certificate'),
        ),
    ]
