# Generated by Django 3.2.12 on 2024-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardskilluser',
            name='level_skill',
            field=models.PositiveIntegerField(choices=[(1, '1'), (1, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
