# Generated by Django 3.2.12 on 2024-11-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_cv', '0002_alter_profile_cv_certifications_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cv',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
