# Generated by Django 5.1.3 on 2024-11-22 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("headhunters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="HeadHunterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "position",
                    models.CharField(
                        help_text="Position within the company", max_length=100
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Company website URL", null=True
                    ),
                ),
                (
                    "linkedin_profile",
                    models.URLField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile photo",
                        null=True,
                        upload_to="profile_photos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headhunter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="action",
            name="headhunter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="headhunters.headhunteruser",
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="headhunter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="headhunters.headhunteruser",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="headhunter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="headhunters.headhunteruser",
            ),
        ),
        migrations.DeleteModel(
            name="HeadHunter",
        ),
    ]
